
HCI_ERROR_CODES = {
    0x00: "Success",
    0x01: "Unknown HCI Command",
    0x02: "Unknown Connection Identifier",
    0x03: "Hardware Failure",
    0x04: "Page Timeout",
    0x05: "Authentication Failure",
    0x06: "PIN or Key Missing",
    0x07: "Memory Capacity Exceeded",
    0x08: "Connection Timeout",
    0x09: "Connection Limit Exceeded",
    0x0A: "Synchronous Connection Limit To A Device Exceeded",
    0x0B: "Connection Already Exists",
    0x0C: "Command Disallowed",
    0x0D: "Connection Rejected due to Limited Resources",
    0x0E: "Connection Rejected Due To Security Reasons",
    0x0F: "Connection Rejected due to Unacceptable BD_ADDR",
    0x10: "Connection Accept Timeout Exceeded",
    0x11: "Unsupported Feature or Parameter Value",
    0x12: "Invalid HCI Command Parameters",
    0x13: "Remote User Terminated Connection",
    0x14: "Remote Device Terminated Connection due to Low Resources",
    0x15: "Remote Device Terminated Connection due to Power Off",
    0x16: "Connection Terminated By Local Host",
    0x17: "Repeated Attempts",
    0x18: "Pairing Not Allowed",
    0x19: "Unknown LMP PDU",
    0x1A: "Unsupported Remote Feature / Unsupported LMP Feature",
    0x1B: "SCO Offset Rejected",
    0x1C: "SCO Interval Rejected",
    0x1D: "SCO Air Mode Rejected",
    0x1E: "Invalid LMP Parameters / Invalid LL Parameters",
    0x1F: "Unspecified Error",
    0x20: "Unsupported LMP Parameter Value / Unsupported LL Parameter Value",
    0x21: "Role Change Not Allowed",
    0x22: "LMP Response Timeout / LL Response Timeout",
    0x23: "LMP Error Transaction Collision / LL Procedure Collision",
    0x24: "LMP PDU Not Allowed",
    0x25: "Encryption Mode Not Acceptable",
    0x26: "Link Key Cannot Be Changed",
    0x27: "Requested QoS Not Supported",
    0x28: "Instant Passed",
    0x29: "Pairing With Unit Key Not Supported",
    0x2A: "Different Transaction Collision",
    0x2C: "QoS Unacceptable Parameter",
    0x2D: "QoS Rejected",
    0x2E: "Channel Classification Not Supported",
    0x2F: "Insufficient Security",
    0x30: "Parameter Out Of Mandatory Range",
    0x32: "Role Switch Pending",
    0x34: "Reserved Slot Violation",
    0x35: "Role Switch Failed",
    0x36: "Extended Inquiry Response Too Large",
    0x37: "Secure Simple Pairing Not Supported By Host",
    0x38: "Host Busy - Pairing",
    0x39: "Connection Rejected due to No Suitable Channel Found",
    0x3A: "Controller Busy",
    0x3B: "Unacceptable Connection Parameters",
    0x3C: "Advertising Timeout",
    0x3D: "Connection Terminated due to MIC Failure",
    0x3E: "Connection Failed to be Established / Synchronization Timeout",
    0x3F: "MAC Connection Failed",
    0x40: "Coarse Clock Adjustment Rejected but Will Try to Adjust Using Clock Dragging",
    0x41: "Type0 Submap Not Defined",
    0x42: "Unknown Advertising Identifier",
    0x43: "Limit Reached",
    0x44: "Operation Cancelled by Host",
    0x45: "Packet Too Long",
}

HCI_PACKET_TYPES = {
    0x01: "COMMAND",
    0x02: "ACL",
    0x03: "SCO",
    0x04: "EVENT",
    0x05: "ISO",
    0xFF: "VENDOR",
}

# Opcode = (OGF << 10) | OCF. Classic commands follow the Bluetooth Core Spec command tables;
# LE/informational entries were cross-checked against Zephyr's hci_types.h.
HCI_OPCODE_NAMES = {
    0x0401: "Inquiry",
    0x0402: "Inquiry Cancel",
    0x0403: "Periodic Inquiry Mode",
    0x0404: "Exit Periodic Inquiry Mode",
    0x0405: "Create Connection",
    0x0406: "Disconnect",
    0x0407: "Add SCO Connection",
    0x0408: "Create Connection Cancel",
    0x0409: "Accept Connection Request",
    0x040A: "Reject Connection Request",
    0x040B: "Link Key Request Reply",
    0x040C: "Link Key Request Negative Reply",
    0x040D: "PIN Code Request Reply",
    0x040E: "PIN Code Request Negative Reply",
    0x040F: "Change Connection Packet Type",
    0x0411: "Authentication Requested",
    0x0413: "Set Connection Encryption",
    0x0415: "Change Connection Link Key",
    0x0417: "Master Link Key",
    0x0419: "Remote Name Request",
    0x041B: "Read Remote Supported Features",
    0x041D: "Read Remote Version Information",
    0x041F: "Read Clock Offset",
    0x0801: "Hold Mode",
    0x0803: "Sniff Mode",
    0x0804: "Exit Sniff Mode",
    0x0805: "Park Mode",
    0x0806: "Exit Park Mode",
    0x0807: "QoS Setup",
    0x0809: "Role Discovery",
    0x080B: "Switch Role",
    0x080C: "Read Link Policy Settings",
    0x080D: "Write Link Policy Settings",
    0x0C01: "Set Event Mask",
    0x0C03: "Reset",
    0x0C05: "Set Event Filter",
    0x0C08: "Flush",
    0x0C09: "Read PIN Type",
    0x0C0A: "Write PIN Type",
    0x0C0B: "Create New Unit Key",
    0x0C0D: "Read Stored Link Key",
    0x0C11: "Write Stored Link Key",
    0x0C12: "Delete Stored Link Key",
    0x0C13: "Write Local Name",
    0x0C14: "Read Local Name",
    0x0C15: "Read Connection Accept Timeout",
    0x0C16: "Write Connection Accept Timeout",
    0x0C17: "Read Page Timeout",
    0x0C18: "Write Page Timeout",
    0x0C19: "Read Scan Enable",
    0x0C1A: "Write Scan Enable",
    0x0C1B: "Read Page Scan Activity",
    0x0C1C: "Write Page Scan Activity",
    0x0C1D: "Read Inquiry Scan Activity",
    0x0C1E: "Write Inquiry Scan Activity",
    0x0C1F: "Read Authentication Enable",
    0x0C20: "Write Authentication Enable",
    0x0C21: "Read Encryption Mode",
    0x0C22: "Write Encryption Mode",
    0x0C23: "Read Class Of Device",
    0x0C24: "Write Class Of Device",
    0x0C25: "Read Voice Setting",
    0x0C26: "Write Voice Setting",
    0x0C27: "Read Automatic Flush Timeout",
    0x0C28: "Write Automatic Flush Timeout",
    0x0C29: "Read Num Broadcast Retransmissions",
    0x0C2A: "Write Num Broadcast Retransmissions",
    0x0C2B: "Read Hold Mode Activity",
    0x0C2C: "Write Hold Mode Activity",
    0x0C2D: "Read Transmit Power Level",
    0x0C2E: "Read SCO Flow Control Enable",
    0x0C2F: "Write SCO Flow Control Enable",
    0x0C31: "Set Host Controller To Host Flow Control",
    0x0C33: "Host Buffer Size",
    0x0C35: "Host Number Of Completed Packets",
    0x0C36: "Read Link Supervision Timeout",
    0x0C37: "Write Link Supervision Timeout",
    0x0C38: "Read Number Of Supported IAC",
    0x0C39: "Read Current IAC LAP",
    0x0C3A: "Write Current IAC LAP",
    0x0C3B: "Read Page Scan Period Mode",
    0x0C3C: "Write Page Scan Period Mode",
    0x0C3D: "Read Page Scan Mode",
    0x0C3E: "Write Page Scan Mode",
    0x0C52: "Write Extended Inquiry Response",
    0x0C6D: "Write LE Host Support",
    0x1001: "Read Local Version Information",
    0x1002: "Read Local Supported Commands",
    0x1003: "Read Local Supported Features",
    0x1004: "Read Local Extended Features",
    0x1005: "Read Buffer Size",
    0x1009: "Read BD_ADDR",
    0x100B: "Read Local Supported Codecs",
    0x100D: "Read Local Supported Codecs (V2)",
    0x1405: "Read RSSI",
    0x2001: "LE Set Event Mask",
    0x2002: "LE Read Buffer Size",
    0x2003: "LE Read Local Supported Features",
    0x2005: "LE Set Random Address",
    0x2006: "LE Set Advertising Parameters",
    0x2008: "LE Set Advertising Data",
    0x2009: "LE Set Scan Response Data",
    0x200A: "LE Set Advertise Enable",
    0x200B: "LE Set Scan Parameters",
    0x200C: "LE Set Scan Enable",
    0x200D: "LE Create Connection",
    0x200E: "LE Create Connection Cancel",
    0x200F: "LE Read White List Size",
    0x2010: "LE Clear White List",
    0x2013: "LE Connection Update",
    0x2014: "LE Set Host Channel Classification",
    0x2015: "LE Read Channel Map",
    0x2016: "LE Read Remote Features",
    0x2017: "LE Encrypt",
    0x2018: "LE Rand",
    0x2019: "LE Start Encryption",
    0x201A: "LE Long Term Key Request Reply",
    0x201B: "LE Long Term Key Request Negative Reply",
    0x201C: "LE Read Supported States",
    0x2066: "LE Accept CIS Request",
    0x2067: "LE Reject CIS Request",
}
